### ISSUE TITLE
node_moudle是否可移植？

### ISSUE THREAD

**Issue by Jamlee** [ijse/nodejs-docker-image#1]
我在外部装的依赖，在容器里面就会运行出错。我也做了一个php的docker开发环境组，但是转到node就有问题了。

**Comment by ijse** [comment]
node 有些module是可以跨平台的，但有些不是。
所以最好build的时候在容器内npm install

除非平台是一致的。

**Comment by Jamlee** [comment]
@ijse 谢谢。你也玩docker开发环境。能不能加个企鹅保持联系你。

**Comment by ijse** [comment]
好啊，不太常用qq， 换微博吧 http://weibo.com/ijser
